# zk configuration file

# NOTE SETTINGS
# =============
# Defines the default options used when generating new notes.
[note]
language = "en"
default-title = "Untitled"
filename = "{{id}}"
extension = "md"
template = "default.md"
id-charset = "alphanum"
id-length = 4
id-case = "lower"
ignore = [
  ".git/*",
  ".gitignore",
  "log.md"
]

# EXTRA VARIABLES
# ===============
# A dictionary of variables you can use for any custom values when generating
# new notes. They are accessible in templates with {{extra.<key>}}
[extra]
author = "Jacob"

# Journal Group
# -------------
# https://github.com/mickael-menu/zk/blob/main/docs/daily-journal.md
[group.daily]
paths = ["Journal/Daily"]

[group.daily.note]
# %Y-%m-%d is actually the default format, so you could use {{date now}} instead.
filename = "{{date now '%Y-%m-%d'}}"
extension = "md"
template = "daily.md"

[group.weekly]
paths = ["Journal/Weekly"]

[group.weekly.note]
filename = "{{date now '%Y-%W'}}"
extension = "md"
template = "weekly.md"

# MARKDOWN SETTINGS
# =================
[format.markdown]
link-format = "[[{{id}}|{{title}}]]"
link-encode-path = false
link-drop-extension = true
hashtags = true
colon-tags = false
multiword-tags = true


# EXTERNAL TOOLS
# ==============
[tool]

editor = "nvim"
pager = "bat"
fzf-preview = "bat -p --color always {-1}"


# LSP
# ===
#   Configure basic editor integration for LSP-compatible editors.
#   See https://github.com/mickael-menu/zk/blob/main/docs/editors-integration.md
#
[lsp]

[lsp.diagnostics]
wiki-title = "hint"
dead-link = "error"

[lsp.completion]
note-label = "{{title}}"
note-filter-text = "{{title}}"
note-detail = ""


# NAMED FILTERS
# =============
#    A named filter is a set of note filtering options used frequently together.
#
[filter]

# Matches the notes created the last two weeks. For example:
#    $ zk list recents --limit 15
#    $ zk edit recents --interactive
recents = "--sort created- --created-after 'last two weeks'"


# COMMAND ALIASES
# ===============
#   Aliases are user commands called with `zk <alias> [<flags>] [<args>]`.
#
#   The alias will be executed with `$SHELL -c`, please refer to your shell's
#   man page to see the available syntax. In most shells:
#     * $@ can be used to expand all the provided flags and arguments
#     * you can pipe commands together with the usual | character
#
[alias]

# Shortcut to a command.
ls = "zk list -foneline $@"

# Default flags for an existing command.
list = "zk list --quiet $@"

# Edit the last modified note.
editlast = "zk edit --limit 1 --sort modified- $@"

# Edit the notes selected interactively among the notes created the last two weeks.
# This alias doesn't take any argument, so we don't use $@.
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"

# Print paths separated with colons for the notes found with the given
# arguments. This can be useful to expand a complex search query into a flag
# taking only paths. For example:
#   zk list --link-to "`zk path -m potatoe`"
path = "zk list --quiet --format {{path}} --delimiter , $@"

# Show a random note.
lucky = "zk list --quiet --format full --sort random --limit 1"

# Returns the Git history for the notes found with the given arguments.
# Note the use of a pipe and the location of $@.
hist = "zk list --format path --delimiter0 --quiet $@ | xargs -t -0 git log --patch --"

# Edit this configuration file.
conf = '$EDITOR "$ZK_NOTEBOOK_DIR/.zk/config.toml"'

# Edit journal
day = 'zk new --no-input "$ZK_NOTEBOOK_DIR/Journal/Daily"'
wk = 'zk new --no-input "$ZK_NOTEBOOK_DIR/Journal/Weekly"'

# Fuzzy find notes
find = 'zk edit --interactive'

# List all todos
todos = 'zk list --match "todo" --format short'
